import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import HuddleContextProvider from './utils/HuddleContextProvider';
import  Footer from "../../innerComp/Footer";
import  Header from "../../innerComp/header/Header";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <HuddleContextProvider>
          <Header/>
          <div style={{
                  marginTop: '100px'
                }}>{children}</div>
          <Footer />  
        </HuddleContextProvider>
      </body>
    </html>
  );
}
