// Objetivos comunes relacionados con salud mental y bienestar
export const mentalHealthGoals = [
  "Reducir ansiedad",
  "Manejar el estrés",
  "Mejorar el sueño",
  "Dormir 7-8 horas diarias",
  "Reducir rumiación",
  "Mejorar autoestima",
  "Desarrollar habilidades sociales",
  "Manejar la depresión",
  "Procesar un duelo",
  "Mejorar relaciones interpersonales",
  "Comunicación más asertiva",
  "Manejar emociones intensas",
  "Reducir ataques de pánico",
  "Mejorar concentración",
  "Aumentar motivación",
  "Establecer límites saludables",
  "Procesar trauma",
  "Manejar fobias",
  "Mejorar imagen corporal",
  "Desarrollar autocompasión",
  "Reducir perfeccionismo",
  "Manejar adicciones",
  "Mejorar relaciones de pareja",
  "Procesar separación/divorcio",
  "Manejar transiciones de vida",
  "Desarrollar resiliencia",
  "Mejorar gestión del tiempo",
  "Equilibrar vida personal y laboral",
  "Retomar ejercicio regular",
  "Mejorar hábitos alimentarios",
];

