// Profesiones y titulaciones relacionadas con salud mental
export const mentalHealthDegrees = [
  "Psicólogo/a",
  "Psicóloga",
  "Psicólogo",
  "Psiquiatra",
  "Psicoterapeuta",
  "Terapeuta",
  "Counselor",
  "Trabajador/a Social",
  "Trabajadora Social",
  "Trabajador Social",
  "Psicólogo Clínico",
  "Psicóloga Clínica",
  "Psicólogo Educacional",
  "Psicóloga Educacional",
  "Psicólogo Organizacional",
  "Psicóloga Organizacional",
  "Neuropsicólogo/a",
  "Neuropsicóloga",
  "Neuropsicólogo",
  "Psicoanalista",
  "Terapeuta Familiar",
  "Terapeuta de Pareja",
  "Terapeuta Cognitivo-Conductual",
  "Terapeuta Gestalt",
  "Terapeuta Humanista",
  "Terapeuta Sistémico",
  "Terapeuta EMDR",
  "Coach de Salud Mental",
  "Especialista en Adicciones",
  "Especialista en Trauma",
];

