import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../styles/scss/style.scss";
import  Footer from "../innerComp/Footer";
import  Header from "../innerComp/header/Header";
import AppProvider from "../context/AppContext";  
import { ThirdwebProvider } from "thirdweb/react";

const roboto = Roboto({
  weight: '300',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en" className={roboto.className}>
      <body>        
          <div id="main-wrapper">
          <ThirdwebProvider>
            <AppProvider>
                  <Header/>
                  <div className="page-wrapper"
                  style={{
                    marginTop: '50px'
                  }}
                  >
                  <div className="container-fluid">{children}</div>
                  </div>  
                  <Footer />                
            </AppProvider>
          </ThirdwebProvider>
          </div>        
      </body>
  </html>
  );
}
